### ISSUE TITLE
Trim Notifications if body is too long

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback-component-push#102]
In particular, for APNs:

> Apple Push Notification service refuses any notification that exceeds this limit.

node-apn has a method [`Notification.prototype.trim`](https://github.com/argon/node-apn/blob/6da4e0c0218bc34f6da1e85c13508dfb9f1719f7/lib/notification.js#L388-L421) to deal with this.

It would be good to trim the message by default and/or configure this behavior. Which may happen somewhere in [`apns.js`](https://github.com/strongloop/loopback-component-push/blob/master/lib/providers/apns.js#L91-L110) by adding `note.trim()`.

**Comment by voitau** [comment]
Hi, any thoughts on this?

**Comment by superkhau** [comment]
@voitau Would you like to submit a PR instead?

**Comment by superkhau** [comment]
@voitau What do you think about submitting a PR?

**Comment by superkhau** [comment]
Closing as abandoned. If you are still interested in working on this in the future, just ping and we can reopen it then.
