### ISSUE TITLE
EMFILE errors happening recently

### ISSUE THREAD

**Issue by seriousben** [strongloop/loopback-component-push#123]
With the new dependencies update, we've seen some EMFILE errors probably caused a leak of connections happening after some time and a certain number of pushes being sent.

We suspect APN as being the source of this. It could be due to the way we use that module or maybe a bug in it.

**Comment by seriousben** [comment]
It would be possible for this error to go away with the recent updated of the APN package as well.

**Comment by seriousben** [comment]
This does look like an upstream bug: https://github.com/argon/node-apn/issues/408

**Comment by superkhau** [comment]
We should wait for a fix then update `package.json`. @seriousben Please submit a PR when you notice the upstream fix and ping me for review. ;)

**Comment by superkhau** [comment]
@seriousben Are you still running into issue? Can I close this?

**Comment by seriousben** [comment]
#131 will fix this.
