### ISSUE TITLE
Push connector overrides EventEmitter events of a loopback model

### ISSUE THREAD

**Issue by angfal** [strongloop/loopback-component-push#139]
We have a model:
```javascript
// datasources.json
"push": {
  "name": "push",
  "connector": "loopback-component-push",
  "installation": "Installation",
  "notification": "Notification",
  "application": "Application"
}
```
```javascript
// model-config.json
"Push": {
  "dataSource": "push",
  "public": true
}
```
```javascript
// models/push.js
module.exports = function(Push)  {
  Push.on('attached',  function()  {
    // any actions
  });
}
```
The problem is when an application is started, the 'attached' listener is not executed. All listeners are created on the model level are overwritten. It's because loopback mixins the model class:
```javascript
// loopback-datasource-juggler/lib/datasource.js
DataSource.prototype.mixin = function(ModelCtor) {
  var ops = this.operations();
  var DAO = this.DataAccessObject;

  // mixin DAO
  jutil.mixin(ModelCtor, DAO, { proxyFunctions: true, override: true });
  ...
}
```
The 'ModelCtor' is our model, DAO is the push connector's DataAccessObject. The listeners don't work because the DataAccessObject contains EventEmitter functions, which overrides the same functions in the Model

**Comment by angfal** [comment]
I created a pull request for this story

**Comment by superkhau** [comment]
@angfal Can you comment with a link to the relevant PR?

**Comment by angfal** [comment]
https://github.com/strongloop/loopback-component-push/pull/140
