### ISSUE TITLE
Getting JWT Token must be defined, property "token" is undefined in v3.0.0

### ISSUE THREAD

**Issue by kahyoung** [strongloop/loopback-component-push#149]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
I installed `loopback-component-push` on my server (^3.0.0) and set up push notifications using the example code and tutorial as a guide. When I ran the server and attempted to `POST` to create a notification, server crashed.

### Expected result
I expected to receive a notification on my mobile device.

### Actual result (if bug)
Server crashed, with the following error.

```
AssertionError: JWT Token must be defined, property "token" is undefined.
```

### Additional information (Node.js version, LoopBack version, etc)
Loopback ^3.0.0
loopback-component-push ^3.0.0

Everything works fine if I change `loopback-component-push` to `1.5.1`

It looks like the validation is looking at the application's `pushSettings` - but the documentation doesn't mention anything about adding a token object?

**Comment by ilkerc** [comment]
That's the new apple fancy way of security without all these certificate stuff. Checkout #131

**Comment by kahyoung** [comment]
Oh okay, sorry I missed it.

Is there documentation for the new method?

**Comment by ilkerc** [comment]
@kahyoung Check out [here](http://gobiko.com/blog/token-based-authentication-http2-example-apns/). Start reading from "Generate an auth key", then add the following token settings to push-demo.js, you can get rid of the certificate reading stuff

`      description: 'LoopBack Push Notification Demo Application',
      pushSettings: {
        apns: {
          pushOptions: {
            // Extra options can go here for APN
          },
          feedbackOptions: {
            batchFeedback: true,
            interval: 300
          },
          token: {
            keyId: "key_from_developer_page",
            key: "./server/private/notification/apns.p8",
            teamId: "your_team_id"
          },
          bundle: "your_bundle_id"
        }
      }`

**Comment by kahyoung** [comment]
Documentation has been updated on the main loopback site:

http://loopback.io/doc/en/lb3/Push-notifications.html
