### ISSUE TITLE
get error "[Error: read ECONNRESET] code: 'ECONNRESET'" sometimes using Push.notifyByQuery

### ISSUE THREAD

**Issue by yugidazai** [strongloop/loopback-component-push#150]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
Sometimes (not always) Push loopback does not send notifications.
Steps to reproduce:
From my node.js server, I used **async.eachLimit** (4) to call push loopback service's api.
This api sends push using **Push.notifyByQuery** method based on **userId** field.

### Link to sample repo to reproduce issue (if bug)
.

### Expected result
notification should be sent properly.

### Actual result (if bug)
I got error inside **Push.on('error', cb)**
err: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

### Additional information (Node.js version, LoopBack version, etc)
node -v 0.10.40
"loopback": "^2.14.0"
"loopback-component-push": "^1.5.3"
"loopback-connector-mongodb": "^1.11.3"

Firstly, thanks for your great work, and I am using push loopback quite well for a long time.
I set up a cron task to send notification to users everyday and recently many users could not receive notifications sometimes
Please check above info for more details.

**Comment by zbarbuto** [comment]
FWIW I no longer get this after updating to the latest version of push connector.
