### ISSUE TITLE
How to send notification instead of data when using FCM

### ISSUE THREAD

**Issue by demarchisd** [strongloop/loopback-component-push#181]
# Description/Steps to reproduce

Hey!

I'm trying to use the `loopback-component-push` with Firebase Cloud Message (FCM) instead of Google Cloud Message (GCM), since GCM is now deprecated.

In FCM there are two kinds of message: `Notification` and `Data`. [They're better explained here](https://firebase.google.com/docs/cloud-messaging/concept-options), but the main difference is that `Notification`s are displayed in the notification tray, while `Data`s are not.

I'm trying to send notifications using the [example](https://github.com/strongloop/loopback-example-push/). Everything works fine, except that on my App I'm only receiving `Data` messages. In other words, nothing is displayed on the notification tray.

When I send the message from the [FCM Console](https://console.firebase.google.com), the notification is displayed, so I guess I might be missing some configuration here in the `loopback-component-push`.

# Link to reproduction sandbox

The [example](https://github.com/strongloop/loopback-example-push/) can be used as a sandbox.

# Expected result

The notification should be displayed in the notification tray, like it happens when sending the message from the FCM console:
![img_0320](https://user-images.githubusercontent.com/12222328/46306186-ea7c3480-c589-11e8-9140-501d020d073e.jpg)

# Additional information

```
darwin x64 10.6.0
loopback-demo-push@0.0.0 /Users/demarchisd/Projects/_consulta/push-notifications/loopback-example-push/loopback-3.x
├── loopback@3.22.3
├── loopback-boot@2.27.1
├── loopback-component-explorer@2.7.0
├── loopback-component-push@1.7.0
├── loopback-connector-mongodb@1.18.1
```

**Comment by fleita9** [comment]
I'm experiencing the same situation. Did you solve it?

**Comment by demarchisd** [comment]
Hey @fleita9! Unfortunately, no. I ended up using [fcm-node](https://github.com/jlcvp/fcm-node/) instead.
