### ISSUE TITLE
Error Connecting to APNS doesn't show

### ISSUE THREAD

**Issue by cpentra1** [strongloop/loopback-component-push#39]
Hey, 

Followed the documentation provided here:
http://docs.strongloop.com/display/DOC/Creating+push+notifications#Creatingpushnotifications-Configuretheapplicationwithpushsettings

When configuring the loopback server with APNS there is nothing in the documentation that explains you need to specify a port in the push options.  If no port is specified then it is null, causing a connection error (connecting to APNS).  

No error shows in PushModel methods fn callbacks (e.g. notifyByQuery) or by listening for push connector errors, the two methods of catching errors described here:
http://docs.strongloop.com/display/DOC/Creating+push+notifications#Creatingpushnotifications-Errorhandling

Made it very had to debug, since the absence of server errors made everything server-side appear to be working.

**Comment by superkhau** [comment]
@crandmck ^

**Comment by Sequoia** [comment]
The [doc link](http://docs.strongloop.com/display/DOC/Creating+push+notifications#Creatingpushnotifications-Configuretheapplicationwithpushsettings) above is no longer available.

It looks like [this](https://github.com/strongloop/loopback-component-push/blob/master/lib/providers/apns.js#L37-L39) might be a logic error? 
```js
    if (pushOptions.port !== undefined) {
      pushOptions.port = 2195;
    }
```

Possible cases:

1. Users sets `pushOptions.port` to a number/string/etc.
  * outcome: `port` is overridden ✅  
2. User sets `pushOptions.port` to `undefined`
  * outcome: `port` is left `undefined` ⚠️ ❓ 
3. User neglects to set `pushOptions.port` at all
  * outcome: `port` is **not set at all** ⚠️ ❗️ 

I believe the assignment should be moved out of the if block if it's always supposed to run and the if block should be removed completely. @raymondfeng please advise.

**Comment by crandmck** [comment]
FYI, here is the doc section in question: http://loopback.io/doc/en/lb2/Push-notifications.html#configure-the-application-with-push-settings

However, I can't speak to the correct resolution of the above.... 
From http://loopback.io/doc/en/contrib/functional-area-owners.html it looks like @superkhau is now the owner of Push, with backup from @Amir-61 and @gunjpan .
Any help appreciated!
