### ISSUE TITLE
Update push example to 2.x layout

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-component-push#49]
- migrate `/example` contents into a new repo named `loopback-example-push`
- upgrade to 2.x if necessary

**Comment by crandmck** [comment]
Note that https://github.com/strongloop/loopback-example-push exists.  Not sure of its status, since it's somewhat outdated.

**Comment by superkhau** [comment]
Closing as 2.x example exists at https://github.com/strongloop/loopback-example-push
