### ISSUE TITLE
push notification to angularjs app

### ISSUE THREAD

**Issue by yagobski** [strongloop/loopback-component-push#51]
Hi, It is possible to use this module to send push notifications to web app based on angularjs.
I don't found any documentation how to use loopback to send push notifications to web apps.
I want for exemple when i add data from api explorer it send push notifications and in my client view i can listen loopback server. Please share any code or documentation about this topic.

Thanks

**Comment by MiguelGonzalezAravena** [comment]
What about now? Can [this documentation](https://loopback.io/doc/en/lb3/Push-notifications.html) adapt to ionic framework too?
