### ISSUE TITLE
Keeping deviceToken of the installation up to date

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback-component-push#53]
This is a question about what would be the right way to handle ```deviceToken``` expiration and refresh.
Here are two use cases and the ways I assume they are being handled:

1. client submits a new token which is different from the previous one, it will be saved as a separate installation, and will be used to send push notifications; the previous one will be removed eventually as it becomes _gone_ device (based on enabled feedback service support);
2. client submits a token using POST (create), which is the same as the previous one. Second installation will be created, which has the same ```deviceToken```. For the sake of API simplicity it may not make any sense to handle this on client side. Then, on the backend side it requires some simple logic based on search for installation with the same ```deviceToken``` and probably just updating ```modified``` timestamp, however, it will change the POST (create) logic from create to createOrUpdate, which is still different from PUT, as it would not operate with the installation ID.

Could you please validate my assumptions and let me know what would be the good way to handle use case 2.

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details. You will get more responses from community there. In adddition, you can try https://gitter.im/strongloop/loopback for immediate responses.
