### ISSUE TITLE
Push notifications testing strategy

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback-component-push#54]
I wonder if you have any suggestions how to implement testing strategy of push notifications implemented using LoopBack's push component. Use case:
- System sends a push notification with a number to a User. The problem is to make sure that the proper number is sent.

Since the message is sent to a remote service, the first option would be putting man-in-the-middle and validating expectations based on what was caught. That's what can be done with [nock](https://github.com/pgte/nock/) and HTTP, but not for APNs and sockets. [Mitm.js](https://github.com/moll/node-mitm) can handle this on a necessary lower level. However, for testing purposes, we don't want to establish real connection to APNs for a valid app. And that basically means that since a connection will not be established, nothing will ever be sent and caught by Mitm as a result.
I tried to approach this from another angle by verifying that ```Notification``` instance is created, assuming that if it is in database, the framework took care of sending the message properly. However, as per http://docs.strongloop.com/display/LB/Push+notifications regular ```Notifications``` are not saved to database (unless they are scheduled): 

> Notification model to capture notification messages and persist scheduled notifications.

Could you please suggest any ways how to test this in isolation without real APNs communication?

**Comment by Sequoia** [comment]
Closed via strongloop/loopback.io#92
