### ISSUE TITLE
Need add custom provider

### ISSUE THREAD

**Issue by TonnyTao** [strongloop/loopback-component-push#68]
I use other messaging provider instead of gcm. so I have to code like this:

``` javascript
var Provider = require('customprovider');

var PushManager = require('loopback-component-push/lib/push-manager');
PushManager.providers.android_lc = leancloudProvider;
```

It's ugly, any better way?

**Comment by bajtos** [comment]
I don't think we have a first-class API for registering custom messaging providers. @raymondfeng please correct me if I am wrong.

@TonnyTao can you contribute this feature yourself?

**Comment by raymondfeng** [comment]
@TonnyTao Please submit a patch to wrap your code into an API exposed by the loopback-component-push module.
