### ISSUE TITLE
Problem with Xcode 6.1 and registerForRemoteNotificationTypes

### ISSUE THREAD

**Issue by vittoriofoschi** [strongloop/loopback-component-push#71]
The method registerForRemoteNotificationTypes is not compatible with ios8

**Comment by bajtos** [comment]
@vittoriofoschi please provide more details, where did you find `registerForRemoteNotificationTypes`? Is it used by the [example](https://github.com/strongloop/loopback-component-push/tree/master/example/ios)?

@hideya could you please take a look?

**Comment by bajtos** [comment]
This has been already fixed by #67.

**Comment by bajtos** [comment]
Please upgrade to `loopback-component-push@1.4.3`.

**Comment by vittoriofoschi** [comment]
Sorry , registerForRemoteNotificationTypes is in iOS SDK ... in LBPushNotification.m file ...
