### ISSUE TITLE
iOS sample app has inappropriate code to handle push registration

### ISSUE THREAD

**Issue by hideya** [strongloop/loopback-component-push#75]
It doesn't seem appropriate to invoke [UIApplication registerUserNotificationSettings:\] (or [UIApplication registerForRemoteNotificationTypes:] on iOS 7) in [UIApplicationDelegate application:didFinishLaunchingWithOptions:] of AppDelegate.m.

The code example found in [Push notifications for iOS apps](http://docs.strongloop.com/display/public/LB/Push+notifications+for+iOS+apps) doesn't do it.  Instead, reading the iOS SDK code, [UIApplication registerUserNotificationSettings:] is supposed to be invoked as a consequence of an invocation of [LBPushNotification application: didFinishLaunchingWithOptions:\] (which is also done in [UIApplicationDelegate application:didFinishLaunchingWithOptions:]).

It looks that the code is put there to deal with a backward incompatible change regarding [UIApplication registerForRemoteNotificationTypes:] taken place in iOS 8.  The issue should have been fixed inside of the SDK code, but the seemingly temporary patch is done in the demo code to make it work somehow on iOS 8.

I supposed the followings need to be taken place:
(1) Fix the [UIApplication registerForRemoteNotificationTypes:]  issue in the iOS SDK (this issue has been filed as https://github.com/strongloop/loopback-sdk-ios/issues/32#issuecomment-83010182)
(2) Revert the patch done in the iOS sample app (a part of PR #67)

**Comment by bajtos** [comment]
@hideya your plan sounds good to me, can you please make the necessary changes yourself?

**Comment by hideya** [comment]
Sure!  Step (1) has been done by this pull request: https://github.com/strongloop/loopback-sdk-ios/pull/38
I'll work on Step (2) soon.

**Comment by hideya** [comment]
PR #95 which takes care of Step (2)

**Comment by bajtos** [comment]
@hideya Is there anything else to fix as part of this issue? I think it can be closed now, since both PRs were already landed.

**Comment by hideya** [comment]
@bajtos Yes, please close this.  Thank you!
