### ISSUE TITLE
loopback-component-push is not installed

### ISSUE THREAD

**Issue by glesage** [strongloop/loopback-component-push#79]
Hey all,

I'm getting an issue with the example apps (server & server-2.0)

I do `npm install` and all looks good
Then when I `slc run` I get an error:

```
WARNING: LoopBack connector "loopback-component-push" is not installed as any of the following modules:

 ./connectors/loopback-component-push
loopback-connector-loopback-component-push
loopback-component-push

To fix, run:

    npm install loopback-component-push


events.js:72
        throw er; // Unhandled 'error' event
```

Not sure what's going on /:

Thanks!

---
PS: Originally got this issue on my production application, then tried it on the example apps and got the issues as well...

**Comment by dashby3000** [comment]
I am seeing this issue as well with the v.1.5.0 release.  I fell back to v1.4.2 and all was well with it.

**Comment by raymondfeng** [comment]
Patched in 1.5.1. Please try again.

**Comment by glesage** [comment]
Yep seems fixed thanks!

**Comment by farlymedicaboo** [comment]
happen again in v 1.7.0

**Comment by PowerP** [comment]
Also v 3.0.0

**Comment by mamtakb** [comment]
I am getting same error for v3.2.0
