### ISSUE TITLE
MPNS and WNS provider for windows phones

### ISSUE THREAD

**Issue by behrad** [strongloop/loopback-component-push#80]
I can help/create a PR to add MPNS and WNS support, there exists a module for this https://github.com/rs/pushd however I prefer using loopback stack :)

**Comment by bajtos** [comment]
> @behrad I can help/create a PR to add MPNS and WNS support, there exists a module for this https://github.com/rs/pushd

Sounds great, let us know if you need any help to get started.

**Comment by cleever** [comment]
Is there any update on this?

**Comment by superkhau** [comment]
@behrad Are you still working on this?

**Comment by behrad** [comment]
I've a very simple WNS provider here https://github.com/adpdigital/loopback-component-push

**Comment by superkhau** [comment]
Would you like to submit a PR?

**Comment by superkhau** [comment]
@behrad Are you still working on this? Would you like to submit a PR with your additions?
