### ISSUE TITLE
Using `alert` property in android pushes doesn't work

### ISSUE THREAD

**Issue by seriousben** [strongloop/loopback-component-push#82]
Caused by `alert` not being an enumerable property on `Notification`.

Workaround is:
```
 Object.defineProperty(notification, 'alert', {
  value: notification.alert,
  writable: true,
  enumerable: true,
  configurable: true
});
```

**Comment by bajtos** [comment]
@seriousben thank you for reporting the issue. Could you please submit the fix as a pull request and include a unit-test to prevent regressions in the future?

**Comment by seriousben** [comment]
Hi @bajtos - Do you have any suggestions? I feel like this is happening because of `Notification.hideInternalProperties = true;`. What is the right fix do you think?

**Comment by bajtos** [comment]
I'd say you should explicitly copy the `alert` property from LoopBack's Notification to GCM Message here: https://github.com/strongloop/loopback-component-push/blob/bd6d71153d81a8c21e13fe2858ca05910d006ff5/lib/providers/gcm.js#L62-L68

Please update the unit-test too: https://github.com/strongloop/loopback-component-push/blob/bd6d71153d81a8c21e13fe2858ca05910d006ff5/test/gcm.provider.test.js#L28-L44
