### ISSUE TITLE
Test expect(cacheApp).to.have.property(context.installation.appId) fails

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback-component-push#89]
```
  1) PushManager PushManager applicationsCache stores application data:
     Uncaught AssertionError: expected { Object (stub) } to have a property '3d2125c3458476c5088de491bee78711'
      at verify (..../strongloop/loopback-component-push/test/push-manager.test.js:538:36)
```
Did anything relevant change in the framework?

@crandmck @bajtos

**Comment by bajtos** [comment]
> Did anything relevant change in the framework?

I am not aware of any such change.

Perhaps @raymondfeng will know?

**Comment by superkhau** [comment]
@hacksparrow Is this good to close? Are you still working on this?

**Comment by hacksparrow** [comment]
@superkhau not working on this anymore. You can close this, if it cannot be reproduced.

**Comment by superkhau** [comment]
@hacksparrow Closing.
