### ISSUE TITLE
Avoid duplicate deviceToken and installation records

### ISSUE THREAD

**Issue by bachirelkhoury** [strongloop/loopback-component-push#99]
what's the best practice to avoid multiple Installation records for the same deviceToken?
Trying to add a 'before save' observer but almost feels like there must be a different and easier way.

How do you guys handle that?

**Comment by behrad** [comment]
the same here @bachirelkhoury 
I've written an after save which deletes older installations of the **same device**, However haven't get to a well defined "same device" logic yet!
I have found some modules on github which generate a unique device id for IOS/Android which claim to generate the same id across uninstall/reinstall of your app, but not tested them yet.
lemme know if you have found something different

**Comment by bachirelkhoury** [comment]
thanks @behrad for the tip.
Yeah looks like that's the way to go, although in our case I'm trying to avoid deleting anything.
Instead "before save", I'm doing a findOne by deviceToken, if it does exist, I'm updating that record to update userId, and some other properties. 

This way if multiple users (multiple userIds) use the same phone (ie. installation) the phone will only  receive 1 notification, and installation will have the last signed in userId. I'm assuming this is an edge case anyway, multiple users same phone. 

Will see what others say. I was hoping a simple validation for uniqueness would work, but finding it tricky to handle.

**Comment by behrad** [comment]
> I'm doing a findOne by deviceToken, if it does exist, I'm updating that record to update userId, and some other properties

We have the same here, but I've seen Apple APN giving the same phone different deviceTokens ;)

**Comment by bachirelkhoury** [comment]
> We have the same here, but I've seen Apple APN giving the same phone different deviceTokens ;)
Yeah that's true, but when that happens the old deviceToken becomes redundant so APN server will ignore it and won't push a notification there.

But yeah that's a good problem, because now our system thinks the user has a new device. 
A unique deviceId is the key. In fact you reminded me, we used CFUUIDCreate() on iOS and stored it in the keychain. This will persist when you delete and reinstall the app. So you always have the same deviceId (then don't worry about the token changing)/  

Ok it's clearer why this component doesn't try to handle duplicates etc... that concern is at the application level.

**Comment by behrad** [comment]
:+1: @bachirelkhoury
